/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jabber_audio_encoder_AudioReceiveJniApi */

#ifndef _Included_com_jabber_audio_encoder_AudioReceiveJniApi
#define _Included_com_jabber_audio_encoder_AudioReceiveJniApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jabber_audio_encoder_AudioReceiveJniApi
 * Method:    yy_init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jabber_audio_encoder_AudioReceiveJniApi_yy_1init
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_jabber_audio_encoder_AudioReceiveJniApi
 * Method:    yy_rtp_receive_amr
 * Signature: (I)[B
 */
JNIEXPORT jint JNICALL Java_com_jabber_audio_encoder_AudioReceiveJniApi_yy_1rtp_1receive_1speex
  (JNIEnv *, jclass, jint ,jobject);

/*
 * Class:     com_jabber_audio_encoder_AudioReceiveJniApi
 * Method:    yy_exit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jabber_audio_encoder_AudioReceiveJniApi_yy_1exit
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
