/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jabber_jni_Ice_Jni */

#ifndef _Included_com_jabber_jni_Ice_Jni
#define _Included_com_jabber_jni_Ice_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jabber_jni_Ice_Jni
 * Method:    voice_call_init
 * Signature: (Ljava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jabber_jni_Ice_1Jni_voice_1call_1init
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     com_jabber_jni_Ice_Jni
 * Method:    ice_get_info
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jabber_jni_Ice_1Jni_ice_1get_1info
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_jabber_jni_Ice_Jni
 * Method:    voice_call_establish
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jabber_jni_Ice_1Jni_voice_1call_1establish
  (JNIEnv *, jclass, jint, jstring, jstring, jint);

/*
 * Class:     com_jabber_jni_Ice_Jni
 * Method:    voice_call_destoy
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jabber_jni_Ice_1Jni_voice_1call_1destoy
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_jabber_jni_Ice_Jni
 * Method:    ice_send
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_jabber_jni_Ice_1Jni_ice_1send
  (JNIEnv *, jclass, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
