/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jabber_audio_encoder_AudioTransJniApi */

#ifndef _Included_com_jabber_audio_encoder_AudioTransJniApi
#define _Included_com_jabber_audio_encoder_AudioTransJniApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jabber_audio_encoder_AudioTransJniApi
 * Method:    yy_init
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jabber_audio_encoder_AudioTransJniApi_yy_1init
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_jabber_audio_encoder_AudioTransJniApi
 * Method:    yy_rtp_send_amr
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_jabber_audio_encoder_AudioTransJniApi_yy_1rtp_1send_1amr
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_jabber_audio_encoder_AudioTransJniApi
 * Method:    yy_exit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jabber_audio_encoder_AudioTransJniApi_yy_1exit
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
