/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jabber_audio_encoder_AudioWebrtcNs */

#ifndef _Included_com_jabber_audio_encoder_AudioWebrtcNs
#define _Included_com_jabber_audio_encoder_AudioWebrtcNs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jabber_audio_encoder_AudioWebrtcNs
 * Method:    yy_webrtc_ns_initiate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jabber_audio_encoder_AudioWebrtcNs_yy_1webrtc_1ns_1initiate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jabber_audio_encoder_AudioWebrtcNs
 * Method:    yy_webrtc_ns_process
 * Signature: (I[S[S)I
 */
JNIEXPORT jshortArray JNICALL Java_com_jabber_audio_encoder_AudioWebrtcNs_yy_1webrtc_1ns_1process
  (JNIEnv *, jobject, jint, jshortArray  );

/*
 * Class:     com_jabber_audio_encoder_AudioWebrtcNs
 * Method:    yy_webrtc_ns_free
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jabber_audio_encoder_AudioWebrtcNs_yy_1webrtc_1ns_1free
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
