/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jabber_audio_encoder_AudioDecodeSpeex */

#ifndef _Included_com_jabber_audio_encoder_AudioDecodeSpeex
#define _Included_com_jabber_audio_encoder_AudioDecodeSpeex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jabber_audio_encoder_AudioDecodeSpeex
 * Method:    spx_encode_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jabber_audio_encoder_AudioDecodeSpeex_spx_1decode_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_jabber_audio_encoder_AudioDecodeSpeex
 * Method:    spx_encode_frame
 * Signature: (I[B[S)I
 */
JNIEXPORT jshortArray JNICALL Java_com_jabber_audio_encoder_AudioDecodeSpeex_spx_1decode_1frame
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_jabber_audio_encoder_AudioDecodeSpeex
 * Method:    spx_destroy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jabber_audio_encoder_AudioDecodeSpeex_spx_1destroy
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
