/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jabber_audio_encoder_AudioEncodeSpeex */

#ifndef _Included_com_jabber_audio_encoder_AudioEncodeSpeex
#define _Included_com_jabber_audio_encoder_AudioEncodeSpeex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jabber_audio_encoder_AudioEncodeSpeex
 * Method:    yy_speex_encode_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jabber_audio_encoder_AudioEncodeSpeex_yy_1speex_1encode_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_jabber_audio_encoder_AudioEncodeSpeex
 * Method:    yy_speex_encode_frame
 *
 */
JNIEXPORT jint JNICALL Java_com_jabber_audio_encoder_AudioEncodeSpeex_yy_1speex_1encode_1frame
  (JNIEnv *, jobject, jint, jshortArray, jobject);

/*
 * Class:     com_jabber_audio_encoder_AudioEncodeSpeex
 * Method:    yy_speex_destroy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jabber_audio_encoder_AudioEncodeSpeex_yy_1speex_1destroy
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
