/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jabber_audio_encoder_AudioWebrtcAecm */

#ifndef _Included_com_jabber_audio_encoder_AudioWebrtcAecm
#define _Included_com_jabber_audio_encoder_AudioWebrtcAecm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jabber_audio_encoder_AudioWebrtcAecm
 * Method:    yy_webrtc_aecm_initiate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jabber_audio_encoder_AudioWebrtcAecm_yy_1webrtc_1aecm_1initiate
(JNIEnv *env, jobject obj, jint samp_freq);

/*
 * Class:     com_jabber_audio_encoder_AudioWebrtcAecm
 * Method:    yy_webrtc_aecm_process
 * Signature: (I[S[S)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_jabber_audio_encoder_AudioWebrtcAecm_yy_1webrtc_1aecm_1process
  (JNIEnv *, jobject, jint, jshortArray, jshortArray);

/*
 * Class:     com_jabber_audio_encoder_AudioWebrtcAecm
 * Method:    yy_webrtc_aecm_free
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jabber_audio_encoder_AudioWebrtcAecm_yy_1webrtc_1aecm_1free
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
